# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-08 00:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_auto_20170807_1846'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='discipline',
            field=models.CharField(blank=True, max_length=25),
        ),
    ]
