# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-08 00:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_profile_discipline'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='paired',
            field=models.BooleanField(default=False),
        ),
    ]
