# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-06 22:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_secondchoice'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SecondChoice',
            new_name='Random',
        ),
    ]
