# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-06 22:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20170806_1722'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='random',
            name='question',
        ),
        migrations.DeleteModel(
            name='Random',
        ),
    ]
